### ISSUE TITLE
Big reactors are not protected by claims

### ISSUE THREAD

**Issue by Brycey92** [Brycey92/Galaxy-Craft-Issues#1]
Pack version: 1.3.0-1
Date/time: N/A, affected mods and plugins have not updated
Steps to reproduce:
- Make a big reactor
- Claim it
- People can access it without trust

**Comment by xdMatthewbx** [comment]
Steps to fix:

- Locate GriefPrevention config.yml
- Go to Mods part (line 124 for me)
- Add all big reactor block IDs to BlockIdsRequiringAccessTrust
- Restart the server
- Profit

**Comment by Brycey92** [comment]
Fix applied, needs testing.
