### ISSUE TITLE
Ban a bunch of things

### ISSUE THREAD

**Issue by Brycey92** [Brycey92/Galaxy-Craft-Issues#38]
**Pack version**
1.0.3

**Describe the bug**
- [x] The cave illuminator is very overpowered.
- [x] The item barrel is too cheap for what it does.
- [x] Firewood + lapis on a pick results in autosmelt + luck interacting. Ban firewood.
- [x] Energized paste can camouflage literally any block.
- [x] As per #48, secret trap doors, stairs, and ghost blocks.

**Comment by Brycey92** [comment]
Wasn't stealing any credit, just decided to make the issue report. I'll make sure you're credited for those.

**Comment by WillKracke** [comment]
You might have forgotten to ban chunk loaders btw

**Comment by Brycey92** [comment]
That's intentional, as we're trying to give players the ability to load a very limited number of chunks when online, now that we have a beefier server. The chunk loaders, of course, still need testing.

**Comment by Brycey92** [comment]
Cave illuminators, item barrels, firewood, and secret trap doors, stairs, and ghost blocks have been banned in 1.0.3-1.

Energized paste uses its own crafting handler, has no config to disable crafting, and no crafttweaker or modtweaker compatibility. This is going to be interesting.

**Comment by Brycey92** [comment]
I wrote a config option into SecretRooms to allow disabling the energized paste recipe.
