### ISSUE TITLE
Adventure Mode Recipes don't work

### ISSUE THREAD

**Issue by xdMatthewbx** [Brycey92/Galaxy-Craft-Issues#4]
The recipes necessary to this game mode to get items to get back to earth do not function, these recipes are listed here: https://wiki.micdoodle8.com/wiki/Asteroids_Challenge

Steps to reproduce:

- Put one of those recipes in an ingot compressor and watch it not work

Steps to fix:
- Upload the attached files to the server mods
[mods.zip](https://github.com/Brycey92/Galaxy-Craft-Issues/files/822719/mods.zip)
- Delete all old Galacticraft mods from the server
- Restart the server
- Profit

**Comment by Brycey92** [comment]
Fix applied, tested and works on the server and in singleplayer.
