### ISSUE TITLE
Keybinding Changes Not Permanent

### ISSUE THREAD

**Issue by TripleChaos** [Brycey92/Galaxy-Craft-Issues#43]
**Pack version**
1.0.3

**Describe the bug**
Any changes to keybinds using F6 will not saved past a relaunch of the pack

**To reproduce**
1. Open the fancy keybind menu using F6 (by default) and change a keybind
2. Close the game
3. Relaunch the game, the keybinds will be reverted

**Expected behavior**
Changes to the keybinds through F6 should be permanent

**Screenshots and crash reports**
Before
![image](https://user-images.githubusercontent.com/43894334/46693767-c7303580-cbd8-11e8-9054-32c6df618001.png)

After
![image](https://user-images.githubusercontent.com/43894334/46693796-d9aa6f00-cbd8-11e8-8ac9-35953c4b095b.png)

**Additional context**
Bonus pic of the controls not changing in the .minecraft file
![image](https://user-images.githubusercontent.com/43894334/46694096-c3e97980-cbd9-11e8-84d8-a1dec1382067.png)

**Comment by Brycey92** [comment]
https://github.com/MrNerdy42/Keyboard-Wizard/issues/4

**Comment by Brycey92** [comment]
You can apparently "save" the changes by opening and closing the real controls menu. I know this isn't a fix, but at least it makes the keybind GUI usable for now.

**Comment by Brycey92** [comment]
MrNerdy42 has become active again and released version 1.5.3 of the mod, which should fix the issue. Testing is required before marking this issue as solved.

**Comment by Brycey92** [comment]
The issue persists.

**Comment by Brycey92** [comment]
I only had this issue happen to me once after the update, but neither I nor MrNerdy42 can reproduce it. Marking it as fixed again, and needing testing.

**Comment by Brycey92** [comment]
I can no longer reproduce the issue.
