### ISSUE TITLE
Mobs

### ISSUE THREAD

**Issue by WillKracke** [Brycey92/Galaxy-Craft-Issues#45]
**Pack version**
1.0.3

**Is your feature request related to a problem? Please describe.**
The mobs are significantly more difficult presumably to encourage players to use turrets or otherwise make it harder to ignore the nighttime like you normally can. However, especially because of the lack of flight, the mobs are oppressively difficult and pointlessly impossible to deal with to the point that most players will likely find ways to game the system anyway. Personally, I've completely given up on trying to enter the nether because it's impossible to venture out of the starting area at all even with fully maxed tcon armor and weapons, there are just too many mobs for a player to deal with. Especially with how shit food is right now, it would be impossible to fight more than a handful of any mob at a time without healing and fire resist potions, which you can't even gain access to without nether wart, which can't be acquired without exploring the nether. Seriously, it is so unfairly difficult to fight any mob that it's extremely frustrating to leave my base, and I don't even need to mine for most things. A player with full tcon armor and gear shouldn't be worried about dying every time they see more than 2 skeletons.

**Describe the solution you'd like**
See alternatives

**Describe alternatives you've considered**
Ideally, the best solution here would to be a factorio approach, where mobs are normal for the most part but will attack player bases and stronger mobs will only appear in these situations. This is incredibly difficult to implement, so instead I would recommend having mostly normal mobs but a spawn chance for strong enemies with good drops, so new players could avoid them and not die 5 times for every ore they mine, but experienced players would be encouraged to seek them out and mobs wouldn't be trivial.

**Additional context**
Seriously, current mobs are fucking stupid

**Comment by Brycey92** [comment]
We have no way of making normal mobs spawn with tougher mobs, nor can we make raids happen as you want, nor any other selective spawning. We can, however, reduce the difficulty of the mobs in various ways. The full configuration is at `config/roughmobs.cfg`, and I've uploaded the file 1.0.3 uses [here](https://gist.github.com/Brycey92/f25620d8fbc12ae8413587e6bb2bdda9) for easier reference.

**Comment by WillKracke** [comment]
Sent modified cfg for testing

**Comment by Brycey92** [comment]
Implemented modified version of your cfg in 1.0.3-1.
