### ISSUE TITLE
Astral Sorcery Food Perk

### ISSUE THREAD

**Issue by TripleChaos** [Brycey92/Galaxy-Craft-Issues#47]
**Pack version**
1.0.3

**Describe the bug**
One of the perks you can get in Astral Sorcery reduces the amount of food you need to eat. Except it completely reduces the amount of food you need to eat, unless you get hunger or die or something to forcefully lower your hunger.

**To reproduce**
1. Attune yourself to the Vicio constellation (see book)
2. Level up the alignment to at least 2 and unlock the "Bigger Stomach" perk
3. You should not have your hunger deplete from normal actions (running, healing, block breaking, etc.)

**Expected behavior**
The Bigger Stomach perk should not be this OP lol.

**Comment by WillKracke** [comment]
Works for me too so it's not a bug

**Comment by Brycey92** [comment]
Solved in 1.0.4 by removing Astral Sorcery :P
