### ISSUE TITLE
Garden Cloches are insane

### ISSUE THREAD

**Issue by WillKracke** [Brycey92/Galaxy-Craft-Issues#49]
**Pack version**
1.0.3

**Describe the bug**
Garden cloches are absolutely nuts, they only use ~8rf/t and can fill a gold chest with product in under a few hours with only water as an input, no replant time and only takes up 3 blocks.

**Comment by Brycey92** [comment]
Modified to produce at 40% rate using 80rf/t in 1.0.3-1.
