### ISSUE TITLE
ME Systems not protected by claims

### ISSUE THREAD

**Issue by xdMatthewbx** [Brycey92/Galaxy-Craft-Issues#5]
Steps to reproduce:

- Claim an area
- Create an ME System inside the claim
- Ask someone who does not have permissions to that claim to try and open the ME Terminal
- Notice it works

Steps to fix:

- Locate "config.yml" for GriefPrevention
- Find the Mods section
- Add necessary block IDs to the corresponding section
- Profit

**Comment by Brycey92** [comment]
Please create a separate issue for one of these (Airlock controllers or ME systems) and change the name of this one to be the other.
