### ISSUE TITLE
Porkchops and Possibly Other Items not Stacking Into a Furnace's Output Slot as They're Cooked

### ISSUE THREAD

**Issue by Emmett63** [Brycey92/Galaxy-Craft-Issues#55]
**Pack version**
1.0.5

**Describe the bug**
When cooking multiple raw porkchops, after finishing the first one the furnace stops smelting as if the output slot is full. I noticed this does not happen with iron ore to iron ingots. (They stack into the output slot normally.) I didn't test any other items though.

**To reproduce**
1. Place multiple raw porkchops in a furnace with fuel
2. Wait for it to finish cooking the first one
3. Notice it does not begin smelting the rest of the stack and stacking the cooked porkchops in the output slot

**Expected behavior**
The furnace should continuously stack the cooked porkchops into the output slot as it completes cooking raw porkchops.

**Comment by Brycey92** [comment]
This is due to a conflict between FastFurnace and CustomNPCs: https://github.com/Shadows-of-Fire/FastFurnace/issues/6. The solution for now is to remove FastFurnace.

**Comment by Brycey92** [comment]
I partially rewrote FastFurnace to fix this.
